version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  app:
    build:
      context: .
    container_name: spaceships-api
    ports:
      - "8080:8080"
    environment:
#      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_PROFILES_ACTIVE=develop
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - backend

networks:
  backend:
    driver: bridge
