FROM openjdk:21-jdk-slim AS build
RUN apt-get update && apt-get install -y maven && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package
FROM openjdk:21-jdk-slim
WORKDIR /app
COPY --from=build /app/target/spaceships-api-0.0.1-SNAPSHOT.jar /app/spaceships-api.jar
EXPOSE 8080
#ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=develop", "/app/spaceships-api.jar"]
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=prod", "/app/spaceships-api.jar"]
